_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "EEGeneralizedRCNN"
  WEIGHTS: "E:/MaYun/sgf_private/myD2/weights/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_MASK_HEAD:
    NAME: "SGFEdgeMaskHead"
    IN_FEATURES: [ "p2" ]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
