_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "ClusterGeneralizedRCNN"
  WEIGHTS: "E:/MaYun/sgf_private/myD2/weights/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "ClusterRPN"
    MIN_SIZE: 0
  ROI_HEADS:
    NAME: "ClusterStandardROIHeads"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
